import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles.css";
import { TolgeeNextProvider } from "@repo/localization/tolgee/client";
import { getLanguage } from "@repo/localization/tolgee/language";
import { getTolgee } from "@repo/localization/tolgee/server";
import { DesignSystemProvider } from "@repo/ui";
import { Header } from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const language = await getLanguage();
  const tolgee = await getTolgee();
  const staticData = await tolgee.loadRequired();
  return (
    <html lang={language} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TolgeeNextProvider language={language} staticData={staticData}>
          <DesignSystemProvider>
            <div className="relative flex min-h-screen flex-col">
              <Header />
              <main className="flex-1">{children}</main>
            </div>
          </DesignSystemProvider>
        </TolgeeNextProvider>
      </body>
    </html>
  );
}
